import React, { useState } from 'react';
import "../styles/Expense.css";
import { toast } from 'react-toastify';
import { addSupplier, Supplier } from '../Api/SupplierApi'; // Import the API function

const AddSupplier: React.FC = () => {
  const [supplierName, setSupplierName] = useState<string>('');
  const [phone, setPhone] = useState<number | ''>('');
  const [email, setEmail] = useState<string>('');
  const [address, setAddress] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  // const [success, setSuccess] = useState<string | null>(null);

  const handleSave = async () => {
    if (!supplierName || !phone || !email || !address) {
      toast.error('Please fill in all fields.');
      return;
    }

    setLoading(true);
    setError(null);

    const newSupplier: Supplier = {
      // _id: '', // ID will be generated by the server
      supplierName: supplierName,
      phone: phone,
      email: email,
      address: address,
    };

    try {
      await addSupplier(newSupplier);
      toast.success('Supplier added successfully!');
      setSupplierName('');
      setPhone('');
      setEmail('');
      setAddress('');
    } catch (err) {
      toast.error('Failed to add supplier.');
      console.error('Error adding supplier:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="expense-card">
      <h2 className="expense-heading">Add Supplier</h2>
      <div className="form-container">
        <div className="form-row">
          <div className="form-group">
            <label htmlFor="supplierName" className="form-label">Supplier Name</label>
            <input
              type="text"
              id="supplierName"
              value={supplierName}
              onChange={(e) => setSupplierName(e.target.value)}
              className="form-input"
              placeholder="Enter Supplier name"
            />
          </div>
          <div className="form-group">
            <label htmlFor="phone" className="form-label">Phone</label>
            <input
              type="tel"
              id="phone"
              value={phone}
              onChange={(e) => setPhone(e.target.value ? Number(e.target.value) : '')}
              className="form-input"
              placeholder="Enter Your Phone Number"
            />
          </div>
          <div className="form-group">
            <label htmlFor="email" className="form-label">Email</label>
            <input
              type="email"
              id="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="form-input"
              placeholder="Enter Your Email"
            />
          </div>
        </div>
        <div className="form-group">
          <label htmlFor="address" className="form-label">Address</label>
          <textarea
            id="address"
            value={address}
            onChange={(e) => setAddress(e.target.value)}
            className="form-input"
            placeholder="Enter Address"
          />
        </div>
        <button className="save-button" onClick={handleSave} disabled={loading}>
          {loading ? 'Saving...' : 'Save'}
        </button>
        {/* {success && <p className="success-message">{success}</p>} */}
        {error && <p className="error-message">{error}</p>}
      </div>
    </div>
  );
};

export default AddSupplier;
